apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: watch-crd-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: {{ .Values.service.type }}
